# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bb2bf5110c74a85453836283f8fe087e1ef5ea064f97df593cfd147c28d582c3bdd0854968f4e885c70a520068c866070db19bd77cace543c3c8ca1fd0cfb35

test:
  secret_key_base: 0f5bc83066224f4fd21c20771c70ba06dc6a5a04f2ac940271081b193010630a55e4550ff7f20b29fdbb9d1e2c3816a998df0b00f347f568c21a67c23b2f3794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
